name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        if: runner.os == 'Windows'
        uses: actions/setup-python@v4
        with:
          python-version: '>=3.12'
          architecture: 'x64'

      - name: Install OpenBLAS
        if: runner.os == 'Windows'
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.bat
          ./vcpkg/vcpkg install openblas:x64-windows
      - name: Set PYTHON environment variable
        if: runner.os == 'Windows'
        run: echo "PYTHON=${{ env.pythonLocation }}\\python.exe" >> $GITHUB_ENV
      - name: Add Python to PATH
        if: runner.os == 'Windows'
        run: echo "${{ env.pythonLocation }}\\Scripts" >> $GITHUB_PATH
      - name: Install Visual Studio Build Tools
        if: runner.os == 'Windows'
        run: |
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --includeOptional --quiet --norestart"
          choco install mingw --version=8.1.0 --force --params "/InstallDir:C:\mingw"
          echo "C:\mingw\bin" >> $GITHUB_PATH
      - name: Install gfortran on macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install gfortran
          echo "$(brew --prefix gcc)/bin" >> $GITHUB_PATH

      - name: Set macOS deployment target
        if: runner.os == 'macOS'
        run: echo "MACOSX_DEPLOYMENT_TARGET=14.0" >> $GITHUB_ENV

      - name: Build wheels
        env:
          PYTHON: ${{ env.pythonLocation }}\\python.exe
        uses: pypa/cibuildwheel@v2.22.0
        # env:
        #   CIBW_SOME_OPTION: value
        #    ...
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl