name: Build

on: [ push, pull_request ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ ubuntu-latest, windows-latest, macos-13, macos-14 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install gfortran on macOS
        if: runner.os == 'macOS'
        run: |
          if ! command -v gfortran &> /dev/null; then
            echo "Attempting to install gfortran via Homebrew..."
            brew update || echo "Brew update failed, continuing..."
            brew install gfortran
            echo "$(brew --prefix gcc)/bin" >> $GITHUB_PATH
          else
            echo "gfortran already found."
          fi
        shell: bash 
      - name: Set macOS deployment target
        if: runner.os == 'macOS'
        run: |
          if [[ "$(sw_vers -productVersion)" == 13.* ]]; then
            echo "Setting MACOSX_DEPLOYMENT_TARGET=13.0"
            echo "MACOSX_DEPLOYMENT_TARGET=13.0" >> $GITHUB_ENV
          else
            # Default to 14.0 for macos-14 and potentially newer runners
            echo "Setting MACOSX_DEPLOYMENT_TARGET=14.0"
            echo "MACOSX_DEPLOYMENT_TARGET=14.0" >> $GITHUB_ENV
          fi
        shell: bash
      - name: Install cibuildwheel with uv support
        run: |
          pip install cibuildwheel[uv]
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
      - name: Upload wheels artifact
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl